[package]
name = "tower-sessions-ext-sqlx-store"
description = "SQLx session stores for `tower-sessions-ext`."
version = "0.15.0"
edition = "2021"
authors = ["Max Countryman <hello@maxcountryman.com>"]
license = "MIT"
homepage = "https://github.com/maxcountryman/tower-sessions-ext-stores"
keywords = ["axum", "sessions", "cookie", "tower", "sqlx"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/maxcountryman/tower-sessions-ext-stores"
documentation = "https://docs.rs/tower-sessions-ext-sqlx-store"
readme = "README.md"

[features]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]

[dependencies]
async-trait = "0.1.77"
rmp-serde = "1.1.2"
sqlx = { version = "0.8.0", features = ["time", "runtime-tokio"] }
thiserror = "2.0.12"
time = "0.3.31"
tower-sessions-ext-core = { version = "0.14.0", features = ["deletion-task"] }

[dev-dependencies]
axum = "0.8.1"
tower-sessions-ext = "0.14.0"
tokio = { version = "1.32.0", features = ["full"] }
tokio-test = "0.4.3"
serde = "1"

[[example]]
name = "sqlite"
required-features = ["sqlite"]

[[example]]
name = "postgres"
required-features = ["postgres"]

[[example]]
name = "mysql"
required-features = ["mysql"]
